package template

import "fmt"

// Index returns the template for the index.html file.
func Index(url, title, cname string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content="0; url=%[1]s" />
  <script type="text/javascript">
    window.location.href = "%[1]s"
  </script>
  <title>%[2]s</title>
</head>
<body>
  <p><a href="%[1]s">Click here</a> if not redirected automatically.</p>
</body>
</html>
`,
		url,
		title,
	)
}

// CNAME returns the template for the CNAME file.
func CNAME(url, title, cname string) string {
	return cname
}

// README returns the template for the README.md file.
func README(url, title, cname string) string {
	return fmt.Sprintf(`### %[2]s

Redirects to [%[1]s](%[1]s).

###### Automatically generated by [kashav/point](https://github.com/kashav/point).
`,
		url,
		title,
	)
}
