package markup

func GetIndex() string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content="0; url={{.url}}" />
  <title>{{.title}}</title>
</head>
<body>
  <p><a href="{{.url}}">Click here</a> if not redirected automatically.</p>
</body>
</html>`
}

func GetCname() string {
	return "{{.cname}}"
}

func GetReadme() string {
	return `### {{.title}}

Redirects to [{{.url}}]({{.url}}).

###### Automatically generated by [kshvmdn/shorten](https://github.com/kshvmdn/shorten).`
}
