language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make bootstrap install
before_script:
  - make fmt vet lint
script:
  - make test
